title = "Deginner"
baseurl = "http://deginner.com"
languageCode = "en-us"

[params]
  # Meta parameters.
  language = "en"
  encoding = "utf-8"
  keywords = ["Python", "JavaScript", "Decentralized", "Decentralization", "System D", "Systeme D", "Blockchain", "open source"]
  description = "Open source software development for decentralization, blockchains and system D"

  # Top section of the website.
  topAnchor = "top"
  logo = "http://i.imgur.com/MINlVoa.png"
  title = "Deginner"
  tagline = "Building open source things and putting 'D's in the names instead of 'bit's and 'coin's"

  # Top actions. Action format: [text, anchor]
  mainAction = ["Contact Us", "Contact"]
  secondaryAction = ["Projects &nbsp; ›", "Projects"]

[blackfriday]
  hrefTargetBlank = true

[[menu.home]]
    name = "About"
    weight = 1
    identifier = "about"
    url = "#About"
[[menu.home]]
    name = "Projects"
    weight = 2
    url = "#Projects"
[[menu.main]]
    name = "Contact"
    weight = 4
    url = "/contact#Contact"
